# Generated by Django 3.1.2 on 2021-06-08 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='full_address', to='api.useraddress'),
            preserve_default=False,
        ),
    ]
