# Generated by Django 3.1.2 on 2021-06-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_address',
        ),
    ]
