# Generated by Django 3.1.2 on 2021-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_full_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='house_no',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_number',
            field=models.IntegerField(default=1, help_text='E.g. 400006'),
            preserve_default=False,
        ),
    ]
