# Generated by Django 3.1.2 on 2021-06-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210608_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
