# Generated by Django 3.1.2 on 2021-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210608_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
